# Generated by Django 2.2 on 2021-04-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='allUsersInfo',
            new_name='allmessage',
        ),
    ]
