# Generated by Django 2.2 on 2021-04-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20210415_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmessage',
            name='message1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='allmessage',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
