# Generated by Django 2.2 on 2021-04-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusersinfo',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allusersinfo',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allusersinfo',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
