# Generated by Django 2.2 on 2021-04-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_recomendationdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendationdetails',
            name='url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
