# Generated by Django 2.2 on 2021-04-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersideas',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
